site_name: cATO Manifesto
site_url: https://manifesto.rise8.us/
repo_url: https://github.com/rise8-us/cato-manifesto
edit_uri: edit/main/docs/
repo_name: cato-manifesto
theme:
  name: material
  custom_dir: docs/overrides
  logo: images/r8.png
  favicon: images/r8.png
#  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.expand
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rise8-us/cato-manifesto
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
plugins:
  - search
  - git-revision-date-localized:
      type: iso_datetime
  - with-pdf:
      output_path: assets/cATO_Manifesto.pdf
      author: Rise8
      copyright: © 2023
      cover_subtitle: ""
      toc_title: Table of Contents
      toc_level: 1
      ordered_chapter_level: 0
      two_columns_level: 0
  - print-site:
      path_to_pdf: "assets/cATO_Manifesto.pdf"
nav:
  - 'Manifesto': 'index.md'
  - 'The 8 Values': 'the-8-values.md'
  - 'The 12 Principles': 'the-12-principles.md'
  - 'History': 'history.md'
