site_name: cATO Manifesto
site_url: https://rise8-us.github.io/cato-Manifesto
repo_url: https://github.com/rise8-us/cato-Manifesto
edit_uri: edit/main/docs/
repo_name: cato-Manifesto
theme:
  name: material
#  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rise8-us/cato-Manifesto
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
plugins:
  - search
  - print-site
nav:
  - 'Manifesto': 'index.md'
  - 'The 8 Values': 'the-8-values.md'
  - 'The 12 Principles': 'the-12-principles.md'
  - 'History': 'history.md'
